
server:
  port: 80

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:3306/study?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    url: jdbc:mariadb://localhost:3306/study
    username: root
    password: root
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        show_sql: true
        format_sql: true
        # /* */ sql ?? ??
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath*:mapper/*Mapper.xml

logging:
  level:
    # binding ?? ? ??
    org.hibernate.type.descriptor.sql: trace
    # org.springframework.web: debug
    org.springframework: debug
    org.hibernate: info
