
server:
  port: 80

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:3306/study?serverTimezone=UTC
    url: jdbc:mariadb://localhost:3306/study
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        show_sql: true
        format_sql: true
        # /* */ sql ?? ??
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect

logging:
  level:
    # binding ?? ? ??
    org.hibernate.type.descriptor.sql: trace
